spring:
  messages:
    encoding: utf-8

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: on

  mail:
    host: "smtp.mailtrap.io"
    port: 2525
    protocol: 'smtp'
    username: "da88751db1de09"
    password: "740691817b5a20"
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        debug: true



#smuestra toda la auto-configuración en el log
logging:
  level:
    org:
     springframework: debug
     hibernate: debug

