spring:
  messages:
    encoding: utf-8

  session:
    store-type=jdbc:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: on

  security:
    user:
      name: correo
      password: password

  mail:
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        debug: true



#smuestra toda la auto-configuración en el log
logging:
  level:
    org:
     springframework: debug
     hibernate: debug

