spring:
  profiles:
    active: dev
  security:
    user:
      name: correo
      password: password

  datasource:
    username: root
    password: ''
    url: jdbc:mysql://127.0.0.1/colegio_test?createDatabaseIfNotExist=true&useSSL=false

  mail:
    host: "smtp.mailtrap.io"
    port: 2525
    protocol: 'smtp'
    username: "da88751db1de09"
    password: "740691817b5a20"

server:
  port: 8084

